### ISSUE TITLE
[BUG]: Need improved json file detection

### ISSUE THREAD

**Issue by asreimer** [EarthCubeInGeo/resen#78]
[This line of code](https://github.com/EarthCubeInGeo/resen/blob/v2020.2.1/resen/Resen.py#L866) tries to grab any old file in the directory. The `try: except:` does handle every edge case.

For example, if I open my `cores.json` file with `vim` and then fire up resen, I get the following error:

    Traceback (most recent call last):
      File "/home/asreimer/venvs/py37/bin/resen", line 8, in <module>
        sys.exit(main())
      File "/home/asreimer/venvs/py37/lib/python3.7/site-packages/resen/resencmd.py", line 477, in main
        res = resen.Resen()
      File "/home/asreimer/venvs/py37/lib/python3.7/site-packages/resen/Resen.py", line 68, in __init__
        self.valid_cores = self.__get_valid_cores()
      File "/home/asreimer/venvs/py37/lib/python3.7/site-packages/resen/Resen.py", line 870, in __get_valid_cores
        cores.extend(json.load(f))
      File "/usr/lib64/python3.7/json/__init__.py", line 293, in load
        return loads(fp.read(),
      File "/home/asreimer/venvs/py37/lib64/python3.7/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 16: invalid start byte

This is because `vim` creates a `.cores.json.swp` file.

A simple yet robust fix for this would be to replace the `os.listdir` with a `sorted(glob.glob(*.json)` call instead to make sure we are only grabbing the files we expect to be there.

**Comment by asreimer** [comment]
Fixed in #90
